### ISSUE TITLE
LinkedHashSet and LinkedHashMap

### ISSUE THREAD

**Issue by larrydiamond** [larrydiamond/typescriptcollectionsframework#22]
I am looking for somebody to port the LinkedHashSet and LinkedHashMap classes from the Java Collections Framework into this project.

https://docs.oracle.com/javase/8/docs/api/java/util/LinkedHashSet.html
https://docs.oracle.com/javase/8/docs/api/java/util/LinkedHashMap.html

**Comment by frankgiordano** [comment]
Larry I have implemented an initial LinkedHashMap... with basic functionality of get, put, containsKey and Iterator.. I will do a pull request soon. you may want to review my forked version in the meantime if you have time..

**Comment by frankgiordano** [comment]
entered a pull request #29 for LinkedHashMap

**Comment by larrydiamond** [comment]
pulled to master and reviewing - thank you very much!

**Comment by larrydiamond** [comment]
Can you add in test cases for when the LinkedHashMap is constructed and it receives a number of initial elements please?   I modified the constructor to take in initial elements, so the class may need to be modified to properly behave in these scenarios.

Thank you very much!

**Comment by larrydiamond** [comment]
Thanks for the cool discussion on LinkedHashMap Frank - I think the Map class is very close

**Comment by frankgiordano** [comment]
I created pull request #37 which has work to properly handled initial elements sent to LinkedHashMap constructor for populating into the new LinkedHashMap object, a fix with containsValue() method not working, and additional test cover to cover all new changes. Please review and merge.

**Comment by frankgiordano** [comment]
BTW I suggest for you to retitle this thread as "LinkedHashMap" only and create a new thread for "LinkedHashSet".

**Comment by larrydiamond** [comment]
Thank you very much, this looks great, version 3.2.1 has your code, I just need to do some clean up to publish the entire library as version 4.
