### ISSUE TITLE
Please add more tests

### ISSUE THREAD

**Issue by larrydiamond** [larrydiamond/typescriptcollectionsframework#24]
Okay, I realize that as I write this the framework has 90% code coverage, and I'm asking for contributors to add more unit tests.   I realize that most people would be beyond glad with 90% code coverage.   This framework is intended to be embedded into many many other projects, and I would appreciate any pull requests that would capture additional conditions not currently tested.

Unfortunately, tests just show that a line of code was tested, they don't prove that the code does what you really wanted it to do in the first place.

Any assistance would be greatly appreciated.

**Comment by rmd6502** [comment]
I'm taking this one on in my local repo under rmd6502

**Comment by larrydiamond** [comment]
Great, thank you very much and welcome to the project!

**Comment by larrydiamond** [comment]
Reopening to everybody
