### ISSUE TITLE
TreeSet add return value is false instead of true...

### ISSUE THREAD

**Issue by frankgiordano** [larrydiamond/typescriptcollectionsframework#26]
In TreeSet.ts:

  /**
  * Adds the specified element to this set if it is not already present.
  * @param {K} element element to be added to this set
  * @return {boolean} true if this set did not already contain the specified element
  */
  public add (element:K) : boolean {
    const tmp:number = this.datastore.put(element, 1);
    if (tmp === null) {
      return false;
    }

    return true;
  }

“true if this set did not already contain the specified element”

This add() function always returns false when the element is added successfully except when it returns number 1 if the element existed in the map and the older element replaced which means add() function returns true in this case.

**Comment by larrydiamond** [comment]
GASP.   Bug Confirmed.   

Thank you very much, you are absolutely correct and I'm feeling embarrassed today.   

You will be listed as a contributor for finding and reporting this bug with my thanks this weekend.

**Comment by larrydiamond** [comment]
A fix for this confirmed defect has been checked in.   You are now listed as a contributor for this project.   WELCOME!   And thank you ***VERY*** much for finding this defect and reporting it!
