### ISSUE TITLE
Logo request for the project

### ISSUE THREAD

**Issue by larrydiamond** [larrydiamond/typescriptcollectionsframework#27]
This is a great contribution request for a creative person with good graphics skills.    

This project needs a logo.

**Comment by chiangs** [comment]
I'll take a crack at it :)

**Comment by larrydiamond** [comment]
Welcome to the project!   I'll review those today.  Thank you very much for getting involved and contributing to Open Source (and especially to this project :) )

**Comment by larrydiamond** [comment]
Wow - you are really good!   Thank you for getting these done - welcome to the project!   I'm really happy that you chose this project to donate your time and talent.

Give me a day or two to properly update the documentation and get the blue logo into all the places it needs to go to.

**Comment by chiangs** [comment]
Hey that's awesome, thanks!

**Comment by larrydiamond** [comment]
Didn't forget about you, just got caught up in a few things, sorry about the delay.   You're good - we're good, it's all good, life just intervened.

**Comment by larrydiamond** [comment]
Welcome Stephen!   Your logo is the official logo of the project, and is now on the github site, in the class documentation, in the demo project, and on our twitter account.    

Thank you Stephen, you'll find public thank you's on twitter and linkedin, and you are now officially listed as a contributor to the project.

Thank you, and we love it when good people come and donate their time and effort to Open Source projects!
