### ISSUE TITLE
LinkedHashSet

### ISSUE THREAD

**Issue by larrydiamond** [larrydiamond/typescriptcollectionsframework#38]
I am looking for somebody to port the LinkedHashSet class from the Java Collections Framework into this project.

https://docs.oracle.com/javase/8/docs/api/java/util/LinkedHashSet.html

**Comment by frankgiordano** [comment]
see LinkedHashSet Implementation #40 pull request pls review and merge

**Comment by larrydiamond** [comment]
nice, is it possible to implement LinkedHashSet without modifying the constructor for HashSet?

**Comment by frankgiordano** [comment]
i'm going to revise LinkedHashSet and avoid the HashSet constructor..

**Comment by frankgiordano** [comment]
Hi Larry see pull request #42 I believe this should be a cleaner implementation and enough to mark this complete. Please review. thanks, Frank

**Comment by frankgiordano** [comment]
added more changes to the pull request: some minor clean up, added remove method for LinkedHashMap class, fix return of remove method for LinkedHashSet and added more test coverage of the remove functionality for both classes..

**Comment by larrydiamond** [comment]
Really nice work Frank!   Thank you, this is really great!
