### ISSUE TITLE
EvictingQueue

### ISSUE THREAD

**Issue by Lisalevyshalom** [larrydiamond/typescriptcollectionsframework#58]
Have you considered porting the EvictingQueue class from Guava?

**Comment by larrydiamond** [comment]
Very cool idea!   Sure!

**Comment by Lisalevyshalom** [comment]
Awesome!

**Comment by larrydiamond** [comment]
done!   Version 4.4.9 has an EvictingDeque created to match your request.   It's just like EvictingQueue but it also implements the Deque interface as we discussed.

**Comment by Lisalevyshalom** [comment]
Thank you so much!   That's perfect and exactly what we were looking for!
