### ISSUE TITLE
What to feed as an argument to TreeMap for custom Classes?

### ISSUE THREAD

**Issue by pedy711** [larrydiamond/typescriptcollectionsframework#63]
Hi, first of all, I would like to thank you for your great effort to bring together such a nice collection.

However, I am trying to use TreeMap as follows:

    public filterMap: TreeMap<FieldDescription, LinkedList<FieldFilter>> = new TreeMap<FieldDescription, LinkedList<FieldFilter>>(???);

but I don't know what to pass in instead of ???

I looked at the demo, since they were both strings, you have passed in: `Collections.getStringComparator()`

but that gives an error in my case since they are custom classes.

**Comment by larrydiamond** [comment]
Good afternoon.   Thank you very much for the kind words about the framework.   I've found it very helpful in a few projects of mine.   :)

All NavigableMaps needs a Comparator passed into the constructor so it can properly sort the keys.   As you've already found, string and number are done, debugged, and ready for you.

(Okay, good feedback for me, I need to add TreeMap to the node.js demo project so it's easier for everybody to this)

The easy way:
https://github.com/larrydiamond/typescriptcollectionsframework/blob/master/spec/TestCollections.spec.ts

class PetStoreProduct {
  public sku:number;
  public name:string;
  public brand:string;

  constructor (isku:number, iname:string, ibrand:string) {
    this.sku = isku;
    this.name = iname;
    this.brand = ibrand;
  }
}

const nc:Comparator<PetStoreProduct> = Collections.dynamicComparator<PetStoreProduct>("sku");

and if you need to be able to compare on multiple fields (LastName, FirstName for example)

const nc:Comparator<PetStoreProduct> = Collections.dynamicComparator<PetStoreProduct>("sku", "name");

I enjoy eliminating boilerplate code.


But sometimes, you have a very complex object and you need to get very special.   
The framework supports this too, although my apologies for making for write boilerplate code:

In https://github.com/larrydiamond/typescriptcollectionsframework/blob/master/spec/TestTreeMap.spec.ts

 // PetStoreProduct will be used in testing
  class PetStoreProduct {
    private productName:string;
    private price:number;

    public constructor (iName:string, iPrice:number) {
      this.productName = iName;
      this.price = iPrice;
    }

    public getProductName ():string {
      return this.productName;
    }

    public getPrice():number {
      return this.price;
    }
  }


  const alphabeticalSortPetStoreProduct:Comparator<PetStoreProduct> = {
    compare(o1:PetStoreProduct, o2:PetStoreProduct) : number {
      if (o1 === o2)
        return 0;
        if (o1 === undefined)
          return -1;
      if (o1 === null)
        return -1;
        if (o2 === undefined)
          return 1;
      if (o2 === null)
        return 1;
      if (o1.getProductName() === o2.getProductName())
        return 0;
      if (o1.getProductName() === undefined)
        return -1;
        if (o1.getProductName() === null)
          return -1;
      if (o2.getProductName() === undefined)
        return 1;
        if (o2.getProductName() === null)
          return 1;

      if (o1.getProductName() < o2.getProductName())
        return -1;

      return 1;
    }
  };



I hope you find this helpful.   
Thank you for using the framework!   Thank you for your kind words!
Please feel free to follow up with any other questions!

Thank you very much
Larry Diamond

**Comment by larrydiamond** [comment]
I've also created a treeset example in the tutorial project at https://github.com/larrydiamond/typescriptcollectionsframeworktutorial which gives a code example of exactly how to use the comparable classes

**Comment by pedy711** [comment]
Thanks alot :)

**Comment by larrydiamond** [comment]
You are very welcome!   Thank you for asking
